from ._anvil_designer import HomeTemplate
from anvil import *
import plotly.graph_objects as go
import anvil.server
import json
from collections import defaultdict
from ..Password import Password
import anvil.js


class Home(HomeTemplate):
  def __init__(self, **properties):
    # Set Form properties and Data Bindings.
    self.init_components(**properties)
    self.seecash = False
    if(self.seecash==False):
      self.hide_cash()
    else:
      self.view_cash()
    response = anvil.server.call('getDrivers')
    text = response.get_bytes().decode('utf-8')
    drivers = json.loads(text)
    response = anvil.server.call('getTrips')
    text = response.get_bytes().decode('utf-8')
    trips = json.loads(text)
    driversNew = []
    for x in drivers:
      if x != "Joshua/Brian" or x != "NA" or x != "Patrick/Vincent" or x != "N/A":
        driversNew.append(x)
    driverCount = len(driversNew)
    tripCount = len(trips)
    self.driverCount.text = str(driverCount)
    self.tripCount.text = str(tripCount)
    # Step 1: Count the number of trips for each driver
    trip_count = defaultdict(int)
    print(trips)
    grouped_data = defaultdict(list)
    for trip in trips:
      trip_count[trip['name']] += 1
      date_str = trip['date']
      if date_str:
        date = datetime.strptime(date_str[:10], '%Y-%m-%d')
        grouped_data[date].append(entry)

    grouped_data = dict(sorted(grouped_data.items()))

# Print or plot the grouped data
    dates = list(grouped_data.keys())
    counts = [len(group) for group in grouped_data.values()]

# Step 2: Calculate the total amount generated by each driver
    amount_generated = defaultdict(float)
    for trip in trips:
      amount_generated[trip['name']] += float(trip['amount'].strip('$').replace(',', ''))

    total_amount = sum(amount_generated.values())
    total_amount_formatted = "${:,.2f}".format(total_amount)
    self.moneyin.text = total_amount_formatted
# Step 3: Calculate the average amount per trip
    average_amount_per_trip = defaultdict(float)
    for driver, total_amount in amount_generated.items():
      average_amount_per_trip[driver] = total_amount / trip_count[driver] if trip_count[driver] != 0 else 0

# Step 4: Rank the drivers based on the number of trips, amount generated, and average amount per trip
    ranked_drivers_trips = [{'name': driver, 'trips': trips} for driver, trips in sorted(trip_count.items(), key=lambda x: x[1], reverse=True)]
    ranked_drivers_amount = [{'name': driver, 'amount': f"${amount:,.2f}"} for driver, amount in sorted(amount_generated.items(), key=lambda x: x[1], reverse=True)]
    ranked_drivers_average = [{'name': driver, 'average_amount': f"${avg_amount:.2f}"} for driver, avg_amount in sorted(average_amount_per_trip.items(), key=lambda x: x[1], reverse=True)]
    self.repeating_panel_1.items = ranked_drivers_trips
    self.repeating_panel_2.items = ranked_drivers_amount
    primary_color = '#0000FF'
    self.plot_1.data = go.Bar(x=dates, y=counts, marker=dict(color=primary_color),
                        hovertemplate='<b>%{x}</b><br>' + 'Trips: %{y}')
    # Configure the plot layout
    self.plot_1.layout = {
      'title': 'TRIPS PER DAY',
      'xaxis': {
        'title': 'DATE'
      },
      'yaxis': {
        'title': 'TRIPS'
      }
    }
    # Any code you write here will run before the form opens.

  def button_5_click(self, **event_args):
    """This method is called when the button is clicked"""
    if(self.seecash==True):
      nw_frm = Password()
      alert_instance = alert(
        content=nw_frm,
        large=False,
        title=None,
        dismissible=False,
        buttons=[('Cancel', 0)],
        role='outlined'
      )
      if(alert_instance is None):
        self.view_cash()  
      else:
        self.hide_cash()
    else:
      self.hide_cash()

  def view_cash(self, **event_args):
    self.button_5.background = '#DB4437'
    self.button_5.icon = 'fa:eye-slash'
    self.button_5.tooltip = 'hide cash in'
    label_element = anvil.js.get_dom_node(self.moneyin)
    label_element.style.filter = "blur(0px)"
    self.seecash = False

  def hide_cash(self, **event_args):
    self.button_5.background = '#0080FF'
    self.button_5.icon = 'fa:eye'
    self.button_5.tooltip = 'view cash in'
    label_element = anvil.js.get_dom_node(self.moneyin)
    label_element.style.filter = "blur(25px)"
    self.seecash = True
